language: python

python:
- "2.6"
- "2.7"
- "3.4"
- "3.5"
- "3.6"

install:
- pip install -U pip setuptools
# until smbprotocol is in pypi leave this here
- pip install -e git+https://github.com/jborean93/smbprotocol.git@devel#egg=smbprotocol
- pip install .
- pip install -r requirements-test.txt
- pip install python-coveralls

script:
- py.test -v --instafail --pep8 --cov pypsexec --cov-report term-missing

after_success:
- coveralls
