# Windows Server 2016
image: Visual Studio 2017

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\build-scripts\\run_with_compiler.cmd"
  matrix:
  # https://www.appveyor.com/docs/installed-software/#python
  - PYTHON: Python27
  - PYTHON: Python27-x64
  - PYTHON: Python34
  - PYTHON: Python34-x64
  - PYTHON: Python35
  - PYTHON: Python35-x64
  - PYTHON: Python36
  - PYTHON: Python36-x64

init:
- ps: |
    $ErrorActionPreference = "Stop"
    # Override default Python version/architecture
    $env:Path="C:\$env:PYTHON;C:\$env:PYTHON\Scripts;$env:PATH"
    python -c "import platform; print('Python', platform.python_version(), platform.architecture()[0])"

install:
- ps: |
    pip install -U pip setuptools
    # until smbprotocol is in pypi leave this here
    pip install -e git+https://github.com/jborean93/smbprotocol.git@devel#egg=smbprotocol
    pip install .
    pip install -r requirements-test.txt

build: off  # Do not run MSBuild, build stuff at install step

test_script:
- ps: py.test -v --instafail --pep8 --cov pypsexec --cov-report term-missing
